import type { OperatorDeskState } from './types';

const now = new Date().toISOString();

export const seedOperatorDeskState: OperatorDeskState = {
  leads: [
    {
      id: 'lead-empro-followup',
      contractorName: 'Amit Contractor',
      phone: '+91 98111 22445',
      siteLocation: 'Empro Motor Office, Ghaziabad',
      leadSource: 'Referral',
      workType: 'Commercial office execution',
      approxBudget: 1250000,
      timeline: 'Stage payment required this week',
      materialPreference: 'Commercial ply, laminate, hardware and glass coordination',
      labourRequired: true,
      drawingAvailable: true,
      notes: 'Stage payment must be confirmed before further execution.',
      serviceType: 'Full Execution Desk',
      status: 'Payment Pending',
      createdAt: now,
    },
    {
      id: 'lead-material-order',
      contractorName: 'R.K. Interiors',
      phone: '+91 88222 11990',
      siteLocation: 'Greater Noida West',
      leadSource: 'WhatsApp',
      workType: 'Bulk material sourcing',
      approxBudget: 340000,
      timeline: '48 hours after payment',
      materialPreference: 'MR ply, laminate, edge banding and hinges',
      labourRequired: false,
      drawingAvailable: false,
      notes: 'Material payment gate must be fully cleared before purchase.',
      serviceType: 'Material Desk',
      status: 'Waiting',
      createdAt: now,
    },
  ],
  jobs: [
    {
      id: 'job-empro-motor-office',
      siteName: 'Empro Motor Office',
      contractorName: 'Amit Contractor',
      serviceType: 'Full Execution Desk',
      totalValue: 1250000,
      advanceReceived: 420000,
      pendingAmount: 830000,
      paymentGateStatus: 'Pending',
      currentStage: 'Site Execution',
      workCompleted: 'Reception framing, base panel work and first site coordination round.',
      workPending: 'Wall panel completion, furniture installation, final proof pack.',
      materialRequired: 'Laminate sheets, hardware balance, wire management fixtures.',
      labourRequired: '2 carpenters, 1 helper, 1 supervisor.',
      assignedOwner: 'Ranjeet',
      deadline: '2026-06-25',
      blocker: 'Stage payment pending. No further production release.',
      writtenConfirmation: true,
      photosProof: false,
      riskLevel: 'Critical',
      status: 'Payment Pending',
      nextAction: 'Confirm stage payment before further execution.',
      createdAt: now,
    },
    {
      id: 'job-devala-site',
      siteName: 'Devala Site',
      contractorName: 'Site Owner Desk',
      serviceType: 'Site Control Desk',
      totalValue: 620000,
      advanceReceived: 180000,
      pendingAmount: 440000,
      paymentGateStatus: 'Blocked',
      currentStage: 'Site Execution',
      workCompleted: 'Initial site work and material dispatch checks.',
      workPending: 'Proof verification, dispute closure, handover plan.',
      materialRequired: 'To be verified from proof file.',
      labourRequired: 'Supervisor visit only after dispute file update.',
      assignedOwner: 'Operations',
      deadline: '2026-06-22',
      blocker: 'Dispute file incomplete. Proof collection needed.',
      writtenConfirmation: false,
      photosProof: false,
      riskLevel: 'Critical',
      status: 'Disputed',
      nextAction: 'Update dispute file and collect proof.',
      createdAt: now,
    },
    {
      id: 'job-current-shop-production',
      siteName: 'Current Shop Production',
      contractorName: 'AlterCraft Workshop',
      serviceType: 'Production Desk',
      totalValue: 480000,
      advanceReceived: 260000,
      pendingAmount: 220000,
      paymentGateStatus: 'Clear',
      currentStage: 'Production',
      workCompleted: 'Cutting list approved and first carcass batch started.',
      workPending: 'Mica, edge banding, hardware fitting and QC.',
      materialRequired: 'Laminate, edge banding, drawer channels.',
      labourRequired: 'Workshop carpenter batch.',
      assignedOwner: 'Production Desk',
      deadline: '2026-06-20',
      blocker: '',
      writtenConfirmation: true,
      photosProof: true,
      riskLevel: 'Medium',
      status: 'Active',
      nextAction: 'Update cutting/mica/edge banding progress.',
      createdAt: now,
    },
    {
      id: 'job-contractor-material-order',
      siteName: 'Contractor Material Order',
      contractorName: 'R.K. Interiors',
      serviceType: 'Material Desk',
      totalValue: 340000,
      advanceReceived: 0,
      pendingAmount: 340000,
      paymentGateStatus: 'Awaiting 100% Material Payment',
      currentStage: 'Requirement Captured',
      workCompleted: 'Material list captured.',
      workPending: 'Vendor lock and purchase only after payment.',
      materialRequired: 'MR ply, laminate, hinges, edge banding.',
      labourRequired: 'No labour required.',
      assignedOwner: 'Material Desk',
      deadline: '2026-06-19',
      blocker: '100% material payment pending.',
      writtenConfirmation: true,
      photosProof: true,
      riskLevel: 'Medium',
      status: 'Waiting',
      nextAction: 'Collect 100% material payment before procurement.',
      createdAt: now,
    },
    {
      id: 'job-labour-deployment-batch',
      siteName: 'Labour Deployment Batch',
      contractorName: 'NCR Contractor Pool',
      serviceType: 'Labour Desk',
      totalValue: 96000,
      advanceReceived: 30000,
      pendingAmount: 66000,
      paymentGateStatus: 'Clear',
      currentStage: 'Labour Assigned',
      workCompleted: '2 carpenters + 1 helper assigned.',
      workPending: 'Daily attendance, work proof and balance release.',
      materialRequired: 'Client managed.',
      labourRequired: '2 carpenters + 1 helper.',
      assignedOwner: 'Labour Desk',
      deadline: '2026-06-23',
      blocker: '',
      writtenConfirmation: true,
      photosProof: false,
      riskLevel: 'Medium',
      status: 'Active',
      nextAction: 'Mark attendance and collect site proof today.',
      createdAt: now,
    },
  ],
  paymentGates: [
    {
      id: 'gate-empro',
      relatedJobId: 'job-empro-motor-office',
      serviceType: 'Full Execution Desk',
      requiredAmount: 625000,
      receivedAmount: 420000,
      gateStatus: 'Pending',
      paymentRule: 'Stage payment must clear before next work release.',
      nextPaymentDue: '205000',
      proofAvailable: true,
      notes: 'Hold further execution until payment is confirmed.',
    },
    {
      id: 'gate-material-order',
      relatedJobId: 'job-contractor-material-order',
      serviceType: 'Material Desk',
      requiredAmount: 340000,
      receivedAmount: 0,
      gateStatus: 'Awaiting 100% Material Payment',
      paymentRule: 'Material desk requires full material payment before procurement.',
      nextPaymentDue: '340000',
      proofAvailable: false,
      notes: 'No purchase order before full payment.',
    },
    {
      id: 'gate-labour-batch',
      relatedJobId: 'job-labour-deployment-batch',
      serviceType: 'Labour Desk',
      requiredAmount: 25000,
      receivedAmount: 30000,
      gateStatus: 'Clear',
      paymentRule: 'Labour advance must be received before deployment.',
      nextPaymentDue: 'Balance after attendance proof',
      proofAvailable: true,
      notes: 'Daily attendance proof still required.',
    },
  ],
  cashEntries: [
    {
      id: 'cash-empro-advance',
      date: '2026-06-10',
      type: 'Inflow',
      amount: 420000,
      bucket: 'Business Reserve',
      relatedJobId: 'job-empro-motor-office',
      sourceOrPaidTo: 'Empro Motor Office',
      mode: 'Bank',
      proof: true,
      notes: 'Initial advance received.',
    },
    {
      id: 'cash-shop-laminate',
      date: '2026-06-12',
      type: 'Outflow',
      amount: 86000,
      bucket: 'Material',
      relatedJobId: 'job-current-shop-production',
      sourceOrPaidTo: 'Laminate Vendor',
      mode: 'UPI',
      proof: true,
      notes: 'Shop production laminate purchase.',
    },
    {
      id: 'cash-unallocated',
      date: '2026-06-14',
      type: 'Inflow',
      amount: 25000,
      bucket: '',
      relatedJobId: '',
      sourceOrPaidTo: 'Walk-in contractor',
      mode: 'Cash',
      proof: false,
      notes: 'Needs bucket allocation.',
    },
  ],
  labour: [
    {
      id: 'labour-mukesh',
      name: 'Mukesh',
      role: 'Carpenter',
      assignedSite: 'Labour Deployment Batch',
      dailyRate: 1200,
      paymentType: 'Daily',
      attendanceStatus: 'Present',
      advancePaid: 5000,
      workStatus: 'Active',
      reliabilityScore: 84,
      notes: 'Good finishing speed, needs daily photo proof.',
    },
    {
      id: 'labour-ravi',
      name: 'Ravi',
      role: 'Helper',
      assignedSite: 'Labour Deployment Batch',
      dailyRate: 650,
      paymentType: 'Daily',
      attendanceStatus: 'Present',
      advancePaid: 2000,
      workStatus: 'Active',
      reliabilityScore: 72,
      notes: 'Can support loading, cleanup and hardware sorting.',
    },
    {
      id: 'labour-supervisor',
      name: 'Site Supervisor',
      role: 'Supervisor',
      assignedSite: 'Empro Motor Office',
      dailyRate: 1800,
      paymentType: 'Daily',
      attendanceStatus: 'Not Marked',
      advancePaid: 0,
      workStatus: 'Waiting',
      reliabilityScore: 90,
      notes: 'Deploy after payment gate clears.',
    },
  ],
  materials: [
    {
      id: 'mat-laminate-batch',
      itemName: 'Laminate sheets and edge banding',
      relatedJobId: 'job-current-shop-production',
      vendor: 'Local Laminate Vendor',
      quantity: '24 sheets + matching rolls',
      rate: 3580,
      totalCost: 86000,
      clientPaid: true,
      procurementStatus: 'Received',
      deliveryStatus: 'Delivered',
      proof: true,
      notes: 'Use for current shop production batch.',
    },
    {
      id: 'mat-rk-order',
      itemName: 'MR ply and hardware set',
      relatedJobId: 'job-contractor-material-order',
      vendor: 'To be locked',
      quantity: 'Full site list',
      rate: 0,
      totalCost: 340000,
      clientPaid: false,
      procurementStatus: 'Required',
      deliveryStatus: 'Pending',
      proof: false,
      notes: 'Blocked until 100% material payment clears.',
    },
  ],
  siteReports: [
    {
      id: 'report-shop-production',
      date: '2026-06-15',
      siteName: 'Current Shop Production',
      relatedJobId: 'job-current-shop-production',
      labourPresent: '2 carpenters',
      workCompletedToday: 'Cutting and first carcass assembly.',
      workPending: 'Edge banding and hardware fitting.',
      materialUsed: 'Ply and laminate batch one.',
      materialRequired: 'Drawer channel set.',
      photosTaken: true,
      issues: 'No major issue.',
      nextAction: 'QC after edge banding.',
      updateSent: true,
      notes: 'Keep production proof updated.',
    },
  ],
  disputes: [
    {
      id: 'dispute-devala',
      disputeName: 'Devala Site Proof and Payment File',
      relatedJobId: 'job-devala-site',
      personOrCompany: 'Site owner / contractor desk',
      amountAtRisk: 440000,
      assetAtRisk: 'Site work proof, material record and payment balance',
      documentsAvailable: false,
      whatsappProof: true,
      witnesses: 'Site supervisor and labour team',
      currentStatus: 'Proof file incomplete',
      settlementOption: 'Document completed work and propose stage-wise closure.',
      nextLawfulAction: 'Prepare written timeline, proof pack and settlement note.',
      deadline: '2026-06-21',
      notes: 'Do not continue work without written scope and proof file.',
    },
  ],
  updatedAt: now,
};
